### ISSUE TITLE
question about duplication

### ISSUE THREAD

**Issue by StefanoLonardi** [schneebergerlab/plotsr#10]
Hi Manish,
I have a question about interpreting duplications. Here is an example:
[chr01-7Mto14M.pdf](https://github.com/schneebergerlab/plotsr/files/8120693/chr01-7Mto14M.pdf)

How do I interpret the the light blue ribbon corresponding to a duplication? 

The source and the destination of the blue region are the same size, so what is duplicated there? Is that region a tandem repeat? I looked in the paper, and it was not clear either. Maybe I am missing something obvious here.

Stefano

**Comment by mnshgl0110** [comment]
Hi Stefano,

You can find some discussion on this issue here https://github.com/schneebergerlab/syri/issues/58

In short, you can adjust overlap between translocations/duplications in syri using the `--tdmaxolp --uniq --unip` parameters of syri.

However, I would close the issue here as it is not related to plotsr. Please feel free to open an issue in syri's repository if there are still questions.

Manish
