### ISSUE TITLE
how do I set the line width of homologous block

### ISSUE THREAD

**Issue by jxlabWzZ** [schneebergerlab/plotsr#15]
Hi Manish,

I find that the gray line representing SYN has a different width from the INV(yellow line)or DUP/TRANS, although they're all in the ~ 5Kb range.
So，how do I set the line width of homologous block for improving visualization？

thanks very much!

**Comment by mnshgl0110** [comment]
Currently, there is no parameter to adjust this. The values were selected for optimising visualisation at megabase scale, but I can imagine that they may not be optimal for very zoomed in visualisation. I would try to parameterise this.
If you want I can tell you how to edit the source code so that you can set the same line width for your copy of plotsr.

**Comment by jxlabWzZ** [comment]
Thank you for your reply，
Since I only want to show the SYN area, I copied the data, replaced SYN with INV, appended it to the original file, and then set “invcol” to “#CCCCCC” in base.cfg, which seems to solve my problem. It would be nice if we could change it in the original code.
Thanks again.
