### ISSUE TITLE
Plot feature tracks for the query genomes as well?

### ISSUE THREAD

**Issue by yjx1217** [schneebergerlab/plotsr#42]
Dear Developer,

Do all tracks for plotting need to be based on the reference genomic coordinate? Could plotsr plot feature tracks for the query genomes as well? It will be great if this is possible. 

Thanks for the consideration.

Best,
Jia-Xing

**Comment by mnshgl0110** [comment]
Currently, only reference genomic coordinates are supported. The issue is that visualising tracks for multiple genomes simultaneously without making the plot incomprehensible is not trivial.
However, you can try hacking plotsr like below:
```
$tracks.txt
# file	name	tags
reference.snps.sorted.bed     REF_SNPs    bw:10000;nc:black;ns:8;nf:Arial;lc:sienna;lw:1;bc:peachpuff;ba:0.5
query.snps.sorted.bed     QRY_SNPs    bw:10000;nc:black;ns:8;nf:Arial;lc:sienna;lw:1;bc:peachpuff;ba:0.5
```
As long as the chromosome IDs for query track are same as reference genome and the coordinates in the query track file less than the corresponding reference chromosome length, this should work. I have not tested this though :)

**Comment by yjx1217** [comment]
Hi @mnshgl0110 , 

Thanks for the tip! 

Best,
Jia-Xing
