### ISSUE TITLE
plot haplotype resolved genome by plotsr

### ISSUE THREAD

**Issue by Chenglin20170390** [schneebergerlab/plotsr#8]
Hi  Manish,

It's look nice for visualize the SV from different genomes.
 
 However, In my case, I assembly several genomes with two haplotypes,   I wondering whether  I can use plotsr to show samples with two haplotype(different sample with different colour, each sample has two haplotype genomes with same colour).

Also, I can use plotsr to draw figure   no more than 10 genomes. If more than 10 genomes, it will occur errors.

![image](https://user-images.githubusercontent.com/33062118/154959325-854f9a48-06d2-4f31-9bc6-bcaf531f675a.png)

**Comment by mnshgl0110** [comment]
Hi Lin,

>  whether I can use plotsr to show samples with two haplotype

Yes. In the genomes.txt file you can specify chromosome colours for individual genomes/haplotypyes. For example:
```
genome1_hap1.fasta	g1h1	lw:1.5;lc:red
genome1_hap2.fasta	g1h2	lw:1.5;lc:red
genome2_hap1.fasta	g2h1	lw:1.5;lc:blue
genome2_hap2.fasta	g2h2	lw:1.5;lc:blue
```

The issue with more than 10 genomes should be fixed in the newer versions. In case you are having issues in the latest version, then could you please open a new issue for that and also share the error message.

Best
Manish

**Comment by Chenglin20170390** [comment]
Hi Manish,

   Many thanks for your quick reply !!! 

   This question is perfectly solved. I will open a new issue for plotsr with more than 10 genomes.
<img width="463" alt="image" src="https://user-images.githubusercontent.com/33062118/154964067-0c23f779-1d8b-4c0f-a56d-329629a199c7.png">

   Thanks again.
